early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping

  #PAI changes 
  monitor: Good Epochs # quantity to monitor
  patience: 0 # early stopping patience
  mode: "max" # early stopping patience
